### ISSUE TITLE
Horovod Distributed Train Is Not Working

### ISSUE THREAD

**Issue by AlexFly666** [volcano-sh/volcano#2745]
After running the Horovod training with Volcano 1.7, one worker was normal and trained successfully;

After two worker times are running, the task is completed, not normal at present，The pod log prompt

**What happened**:

```bash
2023-03-20 17:36:16.537042: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2023-03-20 17:36:18.128489: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
ssh: Could not resolve hostname horovod-volcano-sothisai-w1-0: Temporary failure in name resolution
--------------------------------------------------------------------------
ORTE was unable to reliably start one or more daemons.
This usually is caused by:

* not finding the required libraries and/or binaries on
  one or more nodes. Please check your PATH and LD_LIBRARY_PATH
  settings, or configure OMPI with --enable-orterun-prefix-by-default

* lack of authority to execute on one or more specified nodes.
  Please verify your allocation and authorities.

* the inability to write startup files into /tmp (--tmpdir/orte_tmpdir_base).
  Please check with your sys admin to determine the correct location to use.

*  compilation of the orted with dynamic libraries when static are required
  (e.g., on Cray). Please check your configure cmd line and consider using
  one of the contrib/platform definitions for your system type.

* an inability to create a connection back to mpirun due to a
  lack of common network interfaces and/or no route found between
  them. Please check network connectivity (including firewalls
  and network routing requirements).
--------------------------------------------------------------------------
````

At two worker pod normal running, enter the pod named worker0, can ssh to worker1

```bash
root@horovod-volcano-ai-w0-0:/workspace# echo $VC_W0_HOSTS:1,$VC_W1_HOSTS:1
horovod-volcano-ai-w0-0.horovod-volcano-ai:1,horovod-volcano-ai-w1-0.horovod-volcano-ai:1
root@horovod-volcano-ai-w0-0:/workspace# 
root@horovod-volcano-ai-w0-0:/workspace# ssh horovod-volcano-ai-w1-0
Warning: Permanently added 'horovod-volcano-ai-w1-0.horovod-volcano-ai,10.244.0.43' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 3.10.0-957.el7.x86_64 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, you can run the 'unminimize' command.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

root@horovod-volcano-ai-w1-0:~# 
````

**What you expected to happen**:
two worker trained successfully

**How to reproduce it (as minimally and precisely as possible)**:
My Vcjob Manifest

```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: horovod-volcano-ai
spec:
  minAvailable: 2
  schedulerName: volcano
  plugins:
    env: []
    svc: []
  policies:
    - event: PodEvicted
      action: RestartJob
  queue: default
  # 作业的task角色
  tasks:
    - replicas: 1
      name: w0
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        metadata:
          labels:
            containerIndex: "0"
            containerType: worker
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - /bin/cat /proc/1/environ| /usr/bin/tr '\0' '\n' | grep -v HOME | /usr/bin/awk
                  -v ex='export ' '{printf ex;print $1}'> /etc/profile.d/ai.sh 
                  && /usr/sbin/sshd
                  && su - alex -c " touch /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/horovod-volcano-ai.worker_0.log"  
                  && sh /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/exec.sh /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/.running 1
                  && su - alex -c "cd /home/alex/ai_2.8.0_example_scripts/tensorflow_test/tf_train/
                  && horovodrun -np 2 -H $VC_W0_HOSTS:1,$VC_W1_HOSTS:1
                  python '/home/alex/ai_2.8.0_example_scripts/tensorflow_test/tf_train/mnist_horovod.py'
                  > /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/horovod-volcano-ai.worker_0.log
                  2>&1"; rm -rf /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/.running
              image: image.fly.com:5000/gpu/admin/tfhorovod/tensorflow:1.15-cuda11.8-py3.8-gloo
              name: w0
              ports:
                - containerPort: 2222
                  name: w0-port
              resources:
                limits:
                  cpu: "1"
                  memory: 8Gi
                  nvidia.com/gpu: "1"
                requests:
                  cpu: "1"
                  memory: 8Gi
                  nvidia.com/gpu: "1"
              volumeMounts:
                - mountPath: /home/alex
                  name: scriptpath
                - mountPath: /etc/localtime
                  name: localtime
                  readOnly: true
                - mountPath: /etc/sudoers.d/ai_sudo
                  name: sudoerv
                - mountPath: /etc/passwd
                  name: passwdv
                - mountPath: /etc/group
                  name: groupv
                - mountPath: /etc/shadow
                  name: shadowv
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /etc/tmp
                  name: tmpv
                - mountPath: /usr/bin/kubectl
                  name: kubecntr
          nodeSelector:
            resourceGroup: normal
          restartPolicy: Never
          volumes:
            - hostPath:
                path: /home/alex
                type: ""
              name: scriptpath
            - hostPath:
                path: /etc/localtime
                type: ""
              name: localtime
            - hostPath:
                path: /home/alex/.ai_user_info/ai_sudoer
                type: ""
              name: sudoerv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_passwd
                type: ""
              name: passwdv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_group
                type: ""
              name: groupv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_shadow
                type: ""
              name: shadowv
            - emptyDir:
                medium: Memory
              name: dshm
            - hostPath:
                path: /etc/tmp
                type: ""
              name: tmpv
            - hostPath:
                path: /usr/bin/kubectl
                type: ""
              name: kubecntr
    - replicas: 1
      dependsOn:
        name:
        - "w0"
      name: w1
      template:
        metadata:
          labels:
            containerIndex: "1"
            containerType: worker
        spec:
          containers:
            - command:
              - /bin/sh
              - -c
              - sleep 30 && /bin/cat /proc/1/environ| /usr/bin/tr '\0' '\n' | grep -v HOME | /usr/bin/awk -v ex='export ' '{printf ex;print $1}'> /etc/profile.d/ai.sh
               && /usr/sbin/sshd
               && su - alex -c " touch /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/horovod-volcano-ai.worker_1.log"
               && echo '训练详情请查看worker0的日志！' >> /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/horovod-volcano-ai.worker_1.log
               && sh /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/podStatusCheck.sh /home/alex/ai/tensorflow/tf_task/TF_Horovod-02/.running horovod-volcano-sothisai-w1-0.horovod-volcano-sothisai
               && sleep 3600
              image: image.fly.com:5000/gpu/admin/tfhorovod/tensorflow:1.15-cuda11.8-py3.8-gloo
              name: w1
              ports:
                - containerPort: 2222
                  name: w1-port
              resources:
                limits:
                  cpu: "2"
                  memory: 4Gi
                  nvidia.com/gpu: "1"
                requests:
                  cpu: "2"
                  memory: 4Gi
                  nvidia.com/gpu: "1"
              volumeMounts:
                - mountPath: /home/alex
                  name: scriptpath
                - mountPath: /etc/localtime
                  name: localtime
                  readOnly: true
                - mountPath: /etc/sudoers.d/ai_sudo
                  name: sudoerv
                - mountPath: /etc/passwd
                  name: passwdv
                - mountPath: /etc/group
                  name: groupv
                - mountPath: /etc/shadow
                  name: shadowv
                - mountPath: /dev/shm
                  name: dshm
                - mountPath: /etc/tmp
                  name: tmpv
                - mountPath: /usr/bin/kubectl
                  name: kubecntr
          nodeSelector:
            resourceGroup: normal
          restartPolicy: Never
          volumes:
            - hostPath:
                path: /home/alex
                type: ""
              name: scriptpath
            - hostPath:
                path: /etc/localtime
                type: ""
              name: localtime
            - hostPath:
                path: /home/alex/.ai_user_info/ai_sudoer
                type: ""
              name: sudoerv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_passwd
                type: ""
              name: passwdv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_group
                type: ""
              name: groupv
            - hostPath:
                path: /home/alex/.ai_user_info/ai_shadow
                type: ""
              name: shadowv
            - emptyDir:
                medium: Memory
              name: dshm
            - hostPath:
                path: /etc/tmp
                type: ""
              name: tmpv
            - hostPath:
                path: /usr/bin/kubectl
                type: ""
              name: kubecntr
```

**Anything else we need to know?**:

**Environment**:
- Volcano Version: 1.7
- Kubernetes version (use `kubectl version`): 1.18.6
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):  CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64
- Install tools: kubeadm
- Others: CNI: Flannel

**Comment by wangyang0616** [comment]
I noticed that the problem you shared in WeChat has been resolved, is it convenient to synchronize the latest information, thanks! @AlexFly666

**Comment by AlexFly666** [comment]
I can now perform multiple horovod distributed training (multiple worker) by obtaining the pod ip  @wangyang0616

**Comment by AlexFly666** [comment]
But the problem remains:

```bash
Successfully opened dynamic library libcudart.so.11.0
ssh: Could not resolve hostname horovod-volcano-w1-0: Temporary failure in name resolution
````

If I want to get the pod name to use another problem with the worker

@wangyang0616
