### ISSUE TITLE
Failed to launch mpijob after installing volcano

### ISSUE THREAD

**Issue by nicklhy** [volcano-sh/volcano#452]
Hi everyone,
I am trying to use the gang-scheduler in my k8s/kubeflow cluster and installed volcano following the tutorial [here](https://www.kubeflow.org/docs/use-cases/job-scheduling/) and [here](https://github.com/volcano-sh/volcano).
```shell
$ kubectl get all -n volcano-system 
NAME                                       READY   STATUS      RESTARTS   AGE
pod/volcano-admission-5bd5756f79-5rxkh     1/1     Running     0          24h
pod/volcano-admission-init-nf2mc           0/1     Completed   0          24h
pod/volcano-controllers-687948d9c8-xclv7   1/1     Running     0          24h
pod/volcano-scheduler-79f569766f-bxgnf     1/1     Running     0          24h


NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/volcano-admission-service   ClusterIP   10.107.67.206   <none>        443/TCP   24h


NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/volcano-admission     1/1     1            1           24h
deployment.apps/volcano-controllers   1/1     1            1           24h
deployment.apps/volcano-scheduler     1/1     1            1           24h

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/volcano-admission-5bd5756f79     1         1         1       24h
replicaset.apps/volcano-controllers-687948d9c8   1         1         1       24h
replicaset.apps/volcano-scheduler-79f569766f     1         1         1       24h



NAME                               COMPLETIONS   DURATION   AGE
job.batch/volcano-admission-init   1/1           24s        24h
```
However, some error messages came up when I launched the mpijob. It seems the job queue is not working properly.
```shell
$ kubectl logs -n volcano-system volcano-controllers-687948d9c8-xclv7 --tail 10                                                                                             
I0917 02:26:57.418937       1 queue_controller.go:158] Begin sync queue default
I0917 02:26:57.418960       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been seen or deleted
I0917 02:43:37.419076       1 queue_controller.go:158] Begin sync queue default
I0917 02:43:37.419106       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been seen or deleted
I0917 03:00:17.419234       1 queue_controller.go:158] Begin sync queue default
I0917 03:00:17.419268       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been seen or deleted
I0917 03:16:57.419408       1 queue_controller.go:158] Begin sync queue default
I0917 03:16:57.419431       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been seen or deleted
I0917 03:33:37.419563       1 queue_controller.go:158] Begin sync queue default
I0917 03:33:37.419590       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been seen or deleted
```
The pods are all in "Pending" state
```shell
$ kubectl get pods                 
NAME                                      READY   STATUS    RESTARTS   AGE
mxnet-horovod-job-launcher-7pncv          0/1     Pending   0          159m
mxnet-horovod-job-worker-0                0/1     Pending   0          159m
mxnet-horovod-job-worker-1                0/1     Pending   0          159m
mxnet-horovod-job-worker-2                0/1     Pending   0          159m
mxnet-horovod-job-worker-3                0/1     Pending   0          159m
```
The output of the volcano-scheduler is like below
```shell
$ kubectl logs -n volcano-system volcano-scheduler-79f569766f-bxgnf --tail 20
I0917 03:38:21.543470       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0917 03:38:21.543496       1 enqueue.go:122] Leaving Enqueue ...
I0917 03:38:21.543509       1 allocate.go:43] Enter Allocate ...
I0917 03:38:21.543523       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0917 03:38:21.543544       1 allocate.go:247] Leaving Allocate ...
I0917 03:38:21.543552       1 backfill.go:42] Enter Backfill ...
I0917 03:38:21.543562       1 backfill.go:91] Leaving Backfill ...
I0917 03:38:21.547705       1 session.go:154] Close Session 989f0526-d8fc-11e9-af2b-46b0d5a5c4cd
I0917 03:38:22.548180       1 cache.go:771] There are <1> Jobs, <1> Queues and <7> Nodes in total for scheduling.
I0917 03:38:22.548205       1 session.go:135] Open Session 99386113-d8fc-11e9-af2b-46b0d5a5c4cd with <1> Job and <1> Queues
I0917 03:38:22.548540       1 enqueue.go:43] Enter Enqueue ...
I0917 03:38:22.548553       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0917 03:38:22.548564       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0917 03:38:22.548593       1 enqueue.go:122] Leaving Enqueue ...
I0917 03:38:22.548606       1 allocate.go:43] Enter Allocate ...
I0917 03:38:22.548621       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0917 03:38:22.548642       1 allocate.go:247] Leaving Allocate ...
I0917 03:38:22.548651       1 backfill.go:42] Enter Backfill ...
I0917 03:38:22.548662       1 backfill.go:91] Leaving Backfill ...
I0917 03:38:22.552921       1 session.go:154] Close Session 99386113-d8fc-11e9-af2b-46b0d5a5c4cd
```
Really appreciate if someone can offer some help!

**Comment by k82cn** [comment]
It seems default queue was not created :)

/cc @TommyLike @hzxuzhonghu

**Comment by nicklhy** [comment]
BTW, the mpijob can be launched successfully if I did not add "--enable-gang-scheduling true" in the mpi-operator args [here](https://github.com/kubeflow/mpi-operator/blob/a657fd48119de888ac0bc2733996f7c8ce850348/deploy/mpi-operator.yaml#L193)
```
args: [
    "-alsologtostderr",
    "--kubectl-delivery-image",
    "mpioperator/kubectl-delivery:latest",
    "--enable-gang-scheduling",
    "true"
    ]
```
I guess this means the mpi-operator with original k8s scheduler works well.

**Comment by k82cn** [comment]
> I guess this means the mpi-operator with original k8s scheduler works well.

If there're always enough resource to run all mpijobs, gang-scheduling is not necessary.

**Comment by hzxuzhonghu** [comment]
@nicklhy What's your volcano version?

**Comment by hzxuzhonghu** [comment]
Maybe the `default` queue is deleted by accident. The volcano 0.2, we create the `default` queue during the volcano-scheduler bootstrap.

**Comment by nicklhy** [comment]
@hzxuzhonghu I just installed volcano (maybe two days ago) by `kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml`. That should be the newest version ?

**Comment by TommyLike** [comment]
hey @nicklhy it seems that's not related to the default queue not exists, but your job never get enqueued.
```
I0917 03:38:22.548553       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0917 03:38:22.548564       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
```
you can verify the existence of queue via command `kubectl get queues.scheduling.sigs.dev`

BTW we should not use this yaml `https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml` for tryout since it's used as the development purpose. it will always use the latest image that we can not guarantee that is always work during the cycle, instead you can turn to the release page to get the official release yaml. 
```
https://github.com/volcano-sh/volcano/releases
```

**Comment by nicklhy** [comment]
@TommyLike Thank you for your reply !

I just reinstalled volcano v0.2 like `kubectl apply -f volcano-0.2.yaml` and relaunched my mpijob. But the jobs still remains in pending state.

The existence of "default" queue has been verified
```shell
$ kubectl get queues.scheduling.sigs.dev -o yaml   
apiVersion: v1
items:
- apiVersion: scheduling.sigs.dev/v1alpha2
  kind: Queue
  metadata:
    creationTimestamp: "2019-09-18T01:51:19Z"
    generation: 1
    name: default
    resourceVersion: "4622918"
    selfLink: /apis/scheduling.sigs.dev/v1alpha2/queues/default
    uid: 6ecafdb4-bc7c-4795-ae8f-97af2d54ef00
  spec:
    weight: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
But the volcano-controller is still not able to find the queue
```shell
$ kubectl logs -n volcano-system volcano-scheduler-545cb4fb-fn2jh --tail 20 
I0918 01:58:10.779998       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0918 01:58:10.780016       1 enqueue.go:122] Leaving Enqueue ...
I0918 01:58:10.780025       1 allocate.go:43] Enter Allocate ...
I0918 01:58:10.780033       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0918 01:58:10.780045       1 allocate.go:247] Leaving Allocate ...
I0918 01:58:10.780051       1 backfill.go:42] Enter Backfill ...
I0918 01:58:10.780059       1 backfill.go:91] Leaving Backfill ...
I0918 01:58:10.784410       1 session.go:154] Close Session c45711fe-d9b7-11e9-aa04-0a7ea15a0ea9
I0918 01:58:11.784784       1 cache.go:771] There are <1> Jobs, <1> Queues and <7> Nodes in total for scheduling.
I0918 01:58:11.784807       1 session.go:135] Open Session c4f07012-d9b7-11e9-aa04-0a7ea15a0ea9 with <1> Job and <1> Queues
I0918 01:58:11.785081       1 enqueue.go:43] Enter Enqueue ...
I0918 01:58:11.785091       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0918 01:58:11.785098       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0918 01:58:11.785116       1 enqueue.go:122] Leaving Enqueue ...
I0918 01:58:11.785125       1 allocate.go:43] Enter Allocate ...
I0918 01:58:11.785135       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0918 01:58:11.785148       1 allocate.go:247] Leaving Allocate ...
I0918 01:58:11.785155       1 backfill.go:42] Enter Backfill ...
I0918 01:58:11.785161       1 backfill.go:91] Leaving Backfill ...
I0918 01:58:11.790123       1 session.go:154] Close Session c4f07012-d9b7-11e9-aa04-0a7ea15a0ea9
```
```shell
kubectl logs -n volcano-system volcano-controllers-6f95f57fc-cqrdn --tail 20
I0918 01:51:13.032962       1 garbagecollector.go:83] Starting garbage collector
I0918 01:51:13.133102       1 queue_controller.go:111] QueueController is running ...... 
I0918 01:51:13.133105       1 pg_controller.go:110] PodgroupController is running ...... 
I0918 01:51:13.133164       1 job_controller.go:229] JobController is running ...... 
I0918 01:51:13.133178       1 job_controller.go:233] worker 0 start ...... 
I0918 01:51:13.133180       1 job_controller.go:233] worker 1 start ...... 
I0918 01:51:13.133184       1 job_controller.go:233] worker 2 start ...... 
I0918 01:51:18.998928       1 queue_controller.go:141] Begin sync queue default
I0918 01:51:18.998962       1 queue_controller.go:147] queue default has not been seen or deleted
```

**Comment by hzxuzhonghu** [comment]
> I0918 01:51:18.998962       1 queue_controller.go:147] queue default has not been seen or deleted

This is not a error, it is a misleading warning. It is because the podgroup has not been watched.

BTW, @nicklhy can you see other failure?

**Comment by nicklhy** [comment]
> BTW, @nicklhy can you see other failure?

I did not find any failure logs so far, but noticed the status of the PodGroup looks strange
```shell
$ kubectl get podgroups.scheduling.incubator.k8s.io mxnet-horovod-job -o yaml
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  creationTimestamp: "2019-09-18T03:08:31Z"
  generation: 40
  name: mxnet-horovod-job
  namespace: default
  ownerReferences:
  - apiVersion: kubeflow.org/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: MPIJob
    name: mxnet-horovod-job
    uid: c0eb7ae2-83a6-4fde-9ee0-5b2a574302fb
  resourceVersion: "4648445"
  selfLink: /apis/scheduling.incubator.k8s.io/v1alpha1/namespaces/default/podgroups/mxnet-horovod-job
  uid: 85346146-01f8-432d-8f9f-3ad388503f00
spec:
  minMember: 3
status:
  conditions:
  - lastTransitionTime: "2019-09-18T03:09:10Z"
    message: '3/0 tasks in gang unschedulable: job is not ready, 3 minAvailable.'
    reason: NotEnoughResources
    status: "True"
    transitionID: af6edba7-d9c1-11e9-aa04-0a7ea15a0ea9
    type: Unschedulable
  phase: Inqueue
```
The mpijob I launched is a horovod model training program that requires 2 workers (1 gpu for each worker). I am sure the cluster has enough gpu resources now.

**Comment by hzxuzhonghu** [comment]
would you mind providing more scheduler logs?

**Comment by nicklhy** [comment]
Do you mean the logs of volcano-scheduler ? The logs just keep repeating what I provided previously.
```shell
$ kubectl logs -n volcano-system volcano-scheduler-545cb4fb-fn2jh --tail 50 
I0918 03:40:32.028016       1 backfill.go:91] Leaving Backfill ...
I0918 03:40:32.036335       1 session.go:154] Close Session 10cf2679-d9c6-11e9-aa04-0a7ea15a0ea9
I0918 03:40:33.036693       1 cache.go:771] There are <1> Jobs, <1> Queues and <7> Nodes in total for scheduling.
I0918 03:40:33.036714       1 session.go:135] Open Session 11691d64-d9c6-11e9-aa04-0a7ea15a0ea9 with <1> Job and <1> Queues
I0918 03:40:33.036951       1 enqueue.go:43] Enter Enqueue ...
I0918 03:40:33.036960       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0918 03:40:33.036968       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0918 03:40:33.036985       1 enqueue.go:122] Leaving Enqueue ...
I0918 03:40:33.036994       1 allocate.go:43] Enter Allocate ...
I0918 03:40:33.037004       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0918 03:40:33.037018       1 allocate.go:247] Leaving Allocate ...
I0918 03:40:33.037024       1 backfill.go:42] Enter Backfill ...
I0918 03:40:33.037031       1 backfill.go:91] Leaving Backfill ...
I0918 03:40:33.040848       1 session.go:154] Close Session 11691d64-d9c6-11e9-aa04-0a7ea15a0ea9
I0918 03:40:34.041214       1 cache.go:771] There are <1> Jobs, <1> Queues and <7> Nodes in total for scheduling.
I0918 03:40:34.041235       1 session.go:135] Open Session 12026433-d9c6-11e9-aa04-0a7ea15a0ea9 with <1> Job and <1> Queues
I0918 03:40:34.041476       1 enqueue.go:43] Enter Enqueue ...
I0918 03:40:34.041486       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0918 03:40:34.041493       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0918 03:40:34.041508       1 enqueue.go:122] Leaving Enqueue ...
I0918 03:40:34.041516       1 allocate.go:43] Enter Allocate ...
I0918 03:40:34.041525       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0918 03:40:34.041538       1 allocate.go:247] Leaving Allocate ...
I0918 03:40:34.041545       1 backfill.go:42] Enter Backfill ...
I0918 03:40:34.041551       1 backfill.go:91] Leaving Backfill ...
I0918 03:40:34.046015       1 session.go:154] Close Session 12026433-d9c6-11e9-aa04-0a7ea15a0ea9
I0918 03:40:35.046389       1 cache.go:771] There are <1> Jobs, <1> Queues and <7> Nodes in total for scheduling.
I0918 03:40:35.046408       1 session.go:135] Open Session 129bc43b-d9c6-11e9-aa04-0a7ea15a0ea9 with <1> Job and <1> Queues
I0918 03:40:35.046633       1 enqueue.go:43] Enter Enqueue ...
I0918 03:40:35.046642       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0918 03:40:35.046648       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0918 03:40:35.046667       1 enqueue.go:122] Leaving Enqueue ...
I0918 03:40:35.046676       1 allocate.go:43] Enter Allocate ...
I0918 03:40:35.046687       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0918 03:40:35.046700       1 allocate.go:247] Leaving Allocate ...
I0918 03:40:35.046705       1 backfill.go:42] Enter Backfill ...
I0918 03:40:35.046713       1 backfill.go:91] Leaving Backfill ...
I0918 03:40:35.051150       1 session.go:154] Close Session 129bc43b-d9c6-11e9-aa04-0a7ea15a0ea9
I0918 03:40:36.051494       1 cache.go:771] There are <1> Jobs, <1> Queues and <7> Nodes in total for scheduling.
I0918 03:40:36.051516       1 session.go:135] Open Session 1335233a-d9c6-11e9-aa04-0a7ea15a0ea9 with <1> Job and <1> Queues
I0918 03:40:36.051772       1 enqueue.go:43] Enter Enqueue ...
I0918 03:40:36.051783       1 enqueue.go:58] Added Queue <default> for Job <default/mxnet-horovod-job>
I0918 03:40:36.051790       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0918 03:40:36.051818       1 enqueue.go:122] Leaving Enqueue ...
I0918 03:40:36.051833       1 allocate.go:43] Enter Allocate ...
I0918 03:40:36.051844       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0918 03:40:36.051862       1 allocate.go:247] Leaving Allocate ...
I0918 03:40:36.051872       1 backfill.go:42] Enter Backfill ...
I0918 03:40:36.051881       1 backfill.go:91] Leaving Backfill ...
I0918 03:40:36.055870       1 session.go:154] Close Session 1335233a-d9c6-11e9-aa04-0a7ea15a0ea9
```

**Comment by TommyLike** [comment]
@nicklhy I guess it's all because of the design has changed in the volcano repo while it's not updated in kubeflow, this below is the podgroup the kubeflow created.
```
metadata:
  creationTimestamp: "2019-09-18T03:08:31Z"
  generation: 40
  name: mxnet-horovod-job
  namespace: default
  ownerReferences:
  - apiVersion: kubeflow.org/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: MPIJob
    name: mxnet-horovod-job
    uid: c0eb7ae2-83a6-4fde-9ee0-5b2a574302fb
  resourceVersion: "4648445"
  selfLink: /apis/scheduling.incubator.k8s.io/v1alpha1/namespaces/default/podgroups/mxnet-horovod-job
  uid: 85346146-01f8-432d-8f9f-3ad388503f00
spec:
  minMember: 3
```
while now we need to set the queue name and resource for podgroup now.
```
spec:
  minMember: 3
  minResources:
    cpu: "3"
  queue: queue-name balabale...
```

@k82cn  @hzxuzhonghu someone need to check and sync this in kubeflow project.

**Comment by k82cn** [comment]
> while now we need to set the queue name and resource for podgroup now.

If minResource is nil, it'll be inqueue by default; the default queue name is `default`. Is there anything missed?

**Comment by hzxuzhonghu** [comment]
/assign

I will try to reproduce in my local env.

**Comment by hzxuzhonghu** [comment]
at first glance, i saw the mpi-operator is not working well.

```
I0918 08:01:57.017404       1 mpi_job_controller.go:204] Setting up event handlers
I0918 08:01:57.017591       1 mpi_job_controller.go:338] Starting MPIJob controller
I0918 08:01:57.017606       1 mpi_job_controller.go:341] Waiting for informer caches to sync
E0918 08:01:57.021024       1 reflector.go:134] github.com/kubernetes-sigs/kube-batch/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.PodGroup: podgroups.scheduling.incubator.k8s.io is forbidden: User "system:serviceaccount:mpi-operator:mpi-operator" cannot list resource "podgroups" in API group "scheduling.incubator.k8s.io" at the cluster scope
E0918 08:01:58.028483       1 reflector.go:134] github.com/kubernetes-sigs/kube-batch/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.PodGroup: podgroups.scheduling.incubator.k8s.io is forbidden: User "system:serviceaccount:mpi-operator:mpi-operator" cannot list resource "podgroups" in API group "scheduling.incubator.k8s.io" at the cluster scope
E0918 08:01:59.030590       1 reflector.go:134] github.com/kubernetes-sigs/kube-batch/pkg/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.PodGroup: podgroups.scheduling.incubator.k8s.io is forbidden: User "system:serviceaccount:mpi-operator:mpi-operator" cannot list resource "podgroups" in API group "scheduling.incubator.k8s.io" at the cluster scope

```

**Comment by y1k333** [comment]
Hi @hzxuzhonghu , I have the same problem with kubeflow tf-job-operator, after I added "enable-gang-scheduling=true", my jobs are pending forever and I got these errors from volcano-controllers logs:
```
I0920 21:26:13.783941       1 queue_controller.go:158] Begin sync queue default
I0920 21:26:13.783984       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been 
seen or deleted
I0920 21:42:53.784301       1 queue_controller.go:158] Begin sync queue default
I0920 21:42:53.784357       1 queue_controller.go:133] Error syncing queues "default", retrying. Error: queue default has not been 
seen or deleted
```
And I think the tf-job-operator works fine because from logs I can see that "Finished syncing tfjob \"kubeflow/mnist\"
Also logs from volcano-scheduler are like this:
```
I0920 22:06:01.596943       1 backfill.go:91] Leaving Backfill ...
I0920 22:06:01.608384       1 session.go:154] Close Session d523a501-dbf2-11e9-840c-3e7925f9662a
I0920 22:06:02.608824       1 cache.go:771] There are <4> Jobs, <1> Queues and <2> Nodes in total for scheduling.
I0920 22:06:02.608871       1 session.go:135] Open Session d5be1e06-dbf2-11e9-840c-3e7925f9662a with <4> Job and <1> Queues
I0920 22:06:02.609094       1 enqueue.go:43] Enter Enqueue ...
I0920 22:06:02.609120       1 enqueue.go:58] Added Queue <default> for Job <kubeflow/distributed-training-2-workers>
I0920 22:06:02.609226       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0920 22:06:02.609251       1 enqueue.go:122] Leaving Enqueue ...
I0920 22:06:02.609264       1 allocate.go:43] Enter Allocate ...
I0920 22:06:02.609286       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0920 22:06:02.609303       1 allocate.go:247] Leaving Allocate ...
I0920 22:06:02.609312       1 backfill.go:42] Enter Backfill ...
I0920 22:06:02.609325       1 backfill.go:91] Leaving Backfill ...
I0920 22:06:02.623662       1 session.go:154] Close Session d5be1e06-dbf2-11e9-840c-3e7925f9662a
I0920 22:06:03.624050       1 cache.go:771] There are <4> Jobs, <1> Queues and <2> Nodes in total for scheduling.
I0920 22:06:03.624190       1 session.go:135] Open Session d65907e2-dbf2-11e9-840c-3e7925f9662a with <4> Job and <1> Queues
I0920 22:06:03.624443       1 enqueue.go:43] Enter Enqueue ...
I0920 22:06:03.624465       1 enqueue.go:58] Added Queue <default> for Job <kubeflow/tf-smoke-gpu>
I0920 22:06:03.624478       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0920 22:06:03.624517       1 enqueue.go:122] Leaving Enqueue ...
I0920 22:06:03.624594       1 allocate.go:43] Enter Allocate ...
I0920 22:06:03.624642       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0920 22:06:03.624669       1 allocate.go:247] Leaving Allocate ...
I0920 22:06:03.624684       1 backfill.go:42] Enter Backfill ...
I0920 22:06:03.624700       1 backfill.go:91] Leaving Backfill ...
I0920 22:06:03.639744       1 session.go:154] Close Session d65907e2-dbf2-11e9-840c-3e7925f9662a
I0920 22:06:04.640494       1 cache.go:771] There are <4> Jobs, <1> Queues and <2> Nodes in total for scheduling.
I0920 22:06:04.640532       1 session.go:135] Open Session d6f413c7-dbf2-11e9-840c-3e7925f9662a with <4> Job and <1> Queues
I0920 22:06:04.640789       1 enqueue.go:43] Enter Enqueue ...
I0920 22:06:04.640809       1 enqueue.go:58] Added Queue <default> for Job <kubeflow/distributed-training>
I0920 22:06:04.640825       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0920 22:06:04.640841       1 enqueue.go:122] Leaving Enqueue ...
I0920 22:06:04.640858       1 allocate.go:43] Enter Allocate ...
I0920 22:06:04.640880       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0920 22:06:04.640901       1 allocate.go:247] Leaving Allocate ...
I0920 22:06:04.640913       1 backfill.go:42] Enter Backfill ...
I0920 22:06:04.640931       1 backfill.go:91] Leaving Backfill ...
I0920 22:06:04.654565       1 session.go:154] Close Session d6f413c7-dbf2-11e9-840c-3e7925f9662a
I0920 22:06:05.655072       1 cache.go:771] There are <4> Jobs, <1> Queues and <2> Nodes in total for scheduling.
I0920 22:06:05.655109       1 session.go:135] Open Session d78ef022-dbf2-11e9-840c-3e7925f9662a with <4> Job and <1> Queues
I0920 22:06:05.655403       1 enqueue.go:43] Enter Enqueue ...
I0920 22:06:05.655425       1 enqueue.go:58] Added Queue <default> for Job <kubeflow/tf-smoke-gpu>
I0920 22:06:05.655446       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0920 22:06:05.655462       1 enqueue.go:122] Leaving Enqueue ...
I0920 22:06:05.655476       1 allocate.go:43] Enter Allocate ...
I0920 22:06:05.655499       1 allocate.go:94] Try to allocate resource to 0 Namespaces
I0920 22:06:05.655516       1 allocate.go:247] Leaving Allocate ...
I0920 22:06:05.655525       1 backfill.go:42] Enter Backfill ...
I0920 22:06:05.655538       1 backfill.go:91] Leaving Backfill ...
I0920 22:06:05.684207       1 session.go:154] Close Session d78ef022-dbf2-11e9-840c-3e7925f9662a
```
Do you have any suggestions about how I can resolve this issue? Thanks!

**Comment by hzxuzhonghu** [comment]
@y1k333  I am sure this is because the scheduler name in ` tf-job-operator` is `kube-batch`, but it should be `volcano`

**Comment by hzxuzhonghu** [comment]
The #456 should fix the endless logs in queue-controller

**Comment by y1k333** [comment]
Hi @hzxuzhonghu, thanks very much for replying, I changed the `schedulerName` to `volcano` and now I got these logs:
```
I0921 02:28:25.195655       1 cache.go:771] There are <2> Jobs, <1> Queues and <2> Nodes in total for scheduling.
I0921 02:28:25.195697       1 session.go:135] Open Session 7d0e3a2d-dc17-11e9-840c-3e7925f9662a with <2> Job and <1> Queues
I0921 02:28:25.195949       1 enqueue.go:43] Enter Enqueue ...
I0921 02:28:25.195972       1 enqueue.go:58] Added Queue <default> for Job <kubeflow/podgroup-42c6326f-dc12-11e9-8e16-42010a8a00d1>
I0921 02:28:25.195986       1 enqueue.go:75] Try to enqueue PodGroup to 0 Queues
I0921 02:28:25.196009       1 enqueue.go:122] Leaving Enqueue ...
I0921 02:28:25.196021       1 allocate.go:43] Enter Allocate ...
I0921 02:28:25.196081       1 allocate.go:94] Try to allocate resource to 1 Namespaces
I0921 02:28:25.196100       1 proportion.go:207] Queue <default>: deserved <cpu 0.00, memory 0.00>, allocated <cpu 0.00, memory 0.00>, share <0>
I0921 02:28:25.196219       1 allocate.go:138] Namespace <kubeflow> Queue <default> is overused, ignore it.
I0921 02:28:25.196238       1 allocate.go:149] Namespace <kubeflow> have no queue, skip it
I0921 02:28:25.196275       1 allocate.go:247] Leaving Allocate ...
I0921 02:28:25.196292       1 backfill.go:42] Enter Backfill ...
I0921 02:28:25.196304       1 backfill.go:91] Leaving Backfill ...
I0921 02:28:25.204580       1 session.go:154] Close Session 7d0e3a2d-dc17-11e9-840c-3e7925f9662a
```
Looks like my job still cannot get scheduled.  Do you know what's wrong with this?

**Comment by hzxuzhonghu** [comment]
@y1k333 This is a bug in scheduler, please ref: #461.

ping @k82cn  I am not sure how should we fix it.

**Comment by matthewygf** [comment]
Hi guys,
i have a similar problem, however i am trying the simplest, example/job.yaml
i would just get time out with `vkctl job run -f job.yaml`

i have verified that i have the default queue created in CRD.

can you please advice?

**Comment by hzxuzhonghu** [comment]
@matthewygf I donot think `job.yaml` can be run, it is just a demo show, and the volume does not exist.

**Comment by k82cn** [comment]
>  I donot think job.yaml can be run, it is just a demo show, and the volume does not exist.

@hzxuzhonghu , if we did not support it anymore, let's remove it. That's really wired that we put an example there, but it does not work :(

**Comment by hzxuzhonghu** [comment]
Yep, it is a legacy one. let me remove it.

**Comment by k82cn** [comment]
> Yep, it is a legacy one. let me remove it.

If so, any example for matthewygf@ to have a try?

**Comment by hzxuzhonghu** [comment]
`example/integrations/mpi/mpi-example.yaml` `example/integrations/tensorflow/benchmark/tf-example.yaml` both work, i have tried.

**Comment by hzxuzhonghu** [comment]
@nicklhy I find there are so many bugs in mpi-operator, would suggest you trying volcano job. It has more advanced lifecycle management.

**Comment by nicklhy** [comment]
@hzxuzhonghu Oh, I didn't realize volcano supports such functions before. Maybe you can put more details or a doc url in README.
Anyway, I will let you guys know if it works after trying it.

**Comment by nicklhy** [comment]
@hzxuzhonghu It seems I can not set GPU numbers of the workers. Once I add the following lines in [here](https://github.com/volcano-sh/volcano/blob/59dc80d879d428831b57a4b9707f373b346e25de/example/integrations/mpi/mpi-example.yaml#L49), the job can not be launched.
```shell
resources:
  limits:
    nvidia.com/gpu: 1
```
```shell
$ kubectl describe pods lm-mpi-job-mpimaster-0 
Name:           lm-mpi-job-mpimaster-0
Namespace:      default
Priority:       0
Node:           <none>
Labels:         volcano.sh/job-name=lm-mpi-job
                volcano.sh/job-namespace=default
Annotations:    scheduling.k8s.io/group-name: lm-mpi-job
                volcano.sh/job-name: lm-mpi-job
                volcano.sh/job-version: 0
                volcano.sh/task-spec: mpimaster
Status:         Pending
IP:             
Controlled By:  Job/lm-mpi-job
Containers:
  mpimaster:
    Image:      volcanosh/example-mpi:0.0.1
    Port:       22/TCP
    Host Port:  0/TCP
    Command:
      /bin/sh
      -c
      MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" ","`;
      mkdir -p /var/run/sshd; /usr/sbin/sshd;
      mpiexec --allow-run-as-root --host ${MPI_HOST} -np 2 mpi_hello_world > /home/re;
      
    Environment:  <none>
    Mounts:
      /etc/volcano from lm-mpi-job-svc (rw)
      /root/.ssh from lm-mpi-job-ssh (rw,path=".ssh")
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6n58n (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  lm-mpi-job-ssh:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      lm-mpi-job-ssh
    Optional:  false
  lm-mpi-job-svc:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      lm-mpi-job-svc
    Optional:  false
  default-token-6n58n:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6n58n
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age   From     Message
  ----     ------            ----  ----     -------
  Warning  FailedScheduling  7s    volcano  2/3 tasks in gang unschedulable: job is not ready, 1 Allocated, 2 Pending, 3 minAvailable.: .
```

**Comment by nicklhy** [comment]
Besides, the job would fail if I replace the image and commands of my own needs.
```shell
$ kubectl logs -n mdt volcano-mpi-yolov3-job-mpimaster-0
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
ssh: Could not resolve hostname volcano-mpi-yolov3-job-mpiworker-0: Name or service not known
```
Do I need to do any extra settings related to the network ?
My config looks like below
```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: volcano-mpi-yolov3-job
  namespace: mdt
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 1
      name: mpimaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
          - command:
              - /bin/sh
              - -c
              - |
                MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" ","`;
                mkdir -p /var/run/sshd; /usr/sbin/sshd;
                mpirun --allow-run-as-root -np "2" --host ${MPI_HOST} -bind-to none -map-by slot -x NCCL_IB_DISABLE=1 -x NCCL_DEBUG=INFO -x MXNET_CUDNN_AUTOTUNE_DEFAULT=0 -x NCCL_SOCKET_IFNAME=eth0 -mca pml ob1 -mca btl ^openib python3 tools/train_yolov3.py --network darknet53;
            image: xxxxxx
            name: mpimaster
            ports:
              - containerPort: 22
                name: mpijob-port
            workingDir: /home/work
          restartPolicy: OnFailure
    - replicas: 2
      name: mpiworker
      template:
        spec:
          containers:
          - command:
              - /bin/sh
              - -c
              - |
                mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
            image: xxxxxx
            name: mpiworker
            ports:
              - containerPort: 22
                name: mpijob-port
            workingDir: /home/work
#             resources:
#               limits:
#                 nvidia.com/gpu: 1
          restartPolicy: OnFailure
          nodeSelector:
            # hardware-type: NVIDIAGPU
            gpu-type: v100
```

**Comment by k82cn** [comment]
```
Could not load host key: /etc/ssh/ssh_host_rsa_key
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
```

Should `ssh` use key in `~/.ssh`? By default, we put private & public key in `/root/.ssh` :)

**Comment by k82cn** [comment]
> Maybe you can put more details or a doc url in README.

That's a good idea!

**Comment by nicklhy** [comment]
> ```
> Could not load host key: /etc/ssh/ssh_host_rsa_key
> Could not load host key: /etc/ssh/ssh_host_ecdsa_key
> Could not load host key: /etc/ssh/ssh_host_ed25519_key
> ```
> 
> Should `ssh` use key in `~/.ssh`? By default, we put private & public key in `/root/.ssh` :)

Yeah, this is what I am confused about. I didn't see any doc about the usage or how you designed the volcano jobs. Do I need to prepare the ssh keys in my docker images, or volcano will just insert one into the containers automatically ?
And as the next error shows, the hostname is also not properly set.

> ssh: Could not resolve hostname volcano-mpi-yolov3-job-mpiworker-0: Name or service not known

Are there any naming rules about the job ? Or any other things I should take care ?

**Comment by hzxuzhonghu** [comment]
> Are there any naming rules about the job ? Or any other things I should take care ?

https://github.com/volcano-sh/volcano/blob/9cdbf7e814f8785153e139abeeb983b2121f9a0d/pkg/controllers/job/plugins/svc/svc.go#L174-L198

https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#

**Comment by k82cn** [comment]
> Yeah, this is what I am confused about. I didn't see any doc about the usage or how you designed the volcano jobs. Do I need to prepare the ssh keys in my docker images, or volcano will just insert one into the containers automatically ?

By default, job controller will help to generate ssh private/public for you if `ssh` plugin enabled. Those keys are put into `/root/.ssh` :)

> ssh: Could not resolve hostname volcano-mpi-yolov3-job-mpiworker-0: Name or service not known

We also create headless service for each job; but there're some delay for DNS.

**Comment by k82cn** [comment]
@nicklhy , if there're still issue, please ping me at slack; both k8s slack and volcano-sh slack are ok :)

**Comment by nicklhy** [comment]
@k82cn I finally resolved my problems mentioned above and the main reason is the default user of my custom docker image is not root.
At first, I just changed the ssh service launch command to `sudo /usr/sbin/sshd` and the ssh key error was easily resolved. But the dns error still exists no matter how many times it restarts.
Then, I changed the default user back to root in my Dockerfile. This time, everything runs well. Thus, I guess your DNS settings are only visible to root.

**Comment by matthewygf** [comment]
@hzxuzhonghu  yepp it was, thank you for pointing that out. something went wrong with our core-dns, everything works now thanks a lot.
